version: "3"
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql 
    ports:
      - "3306:3306" 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Seoul"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .docker/mysql:/var/lib/mysql
  mongodb:
    container_name: mongodb
    image: mongo:7.0.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - .docker/mongodb/db:/data/db
      - .docker/mongodb/configdb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  minio:
    image: devruri/fa-mate:minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio_root_user
      - MINIO_ROOT_PASSWORD=minio_root_password
    volumes:
      - .docker/minio:/data
