version: '3.1'

services:
  localstack:
    container_name: minio
    image: localstack/localstack
    network_mode: bridge
    environment:
      - SERVICES=s3
    ports:
      - "9000:4566"
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"